### ISSUE TITLE
read_sim outputs into sub-directory

### ISSUE THREAD

**Issue by ACEnglish** [collaborativebioinformatics/SVTeaser#9]
Looking at your parameter sweep code, I think the default behavior of the `read_sim` command should be to place the simulated reads into a sub-directory. We can use this directory's name to record the parameters which can then be consumed by reporting when we build the DataFrame.

So inside of the `output.svt` `read_sim` will make a sub_directory with structure: `sim_reads_${covparam}_${insertparam}_{readlenparam}_{do this for each of the parameters}`
and place the reads/sam inside of this sub-directory.

Then you can edit the param-sweep so it doesn't have to create the `--out-dir`, and you can remove the `--out-dir` parameter from `read_sim`

**Comment by ntadimeti** [comment]
sounds great! Will push this change in a second

**Comment by ntadimeti** [comment]
done!
